title: Kun Hu # your name (or website title) here
logo: "/images/hukun.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Education Background  
  Graduate School of Chinese Academy of Sciences                           2019.09—2022.06
  Tianjin Polytechnic University (TJPU)                                     2015.09—2019.06
  <br><br>
  Subject Competition Experience  
  School-level "Seeking Cup" Math Competition First Prize                          2016.03
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
